### ISSUE TITLE
Gemspec dependency error

### ISSUE THREAD

**Issue by yoonwaiyan** [ctide/devise_lastseenable#3]
Hi, there is an error while running bundle install to my rails 4.1.0 app. 

```ruby
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.5/lib/bundler.rb:374:in `rescue in load_gemspec_uncached': The gemspec at /Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/devise_lastseenable-d2ac199f2fc3/devise_lastseenable.gemspec is not valid. The validation error was 'duplicate dependency on warden (>= 0), (>= 0) use: (Bundler::InvalidOption)
    add_runtime_dependency 'warden', '>= 0', '>= 0'
```

Seems like there are multiple dependencies in the gemspec file from the source code, so updating the gem from existing 0.0.4 to 0.0.5 couldn't solve the problem. This error doesn't happen before I nuked my rbenv and rerun the bundle install on my apps, it was just a warning back then. I think the warning became an error after the bundle version has been updated to 1.10.5 from 1.7.9.

**Comment by ctide** [comment]
Hello, this should be fixed in aacb48b11a0ff9bd31bced49ab86de76e67df474 and pushed as 0.0.5. Please reopen if you run into further issues.
