### ISSUE TITLE
last_seen has no default

### ISSUE THREAD

**Issue by jhass** [ctide/devise_lastseenable#4]
And thus #2 broke everything for new accounts.

**Comment by ctide** [comment]
Reverted, fixed in 3fdad5e12651be664dffff4b5b8c69b24f89a65a

**Comment by jhass** [comment]
I think some tests would be good so it doesn't break again ;)

**Comment by ctide** [comment]
Yeah. :)

I haven’t really looked at this in a few years, but I’ll try to find some time this week to get some basic coverage added.



On July 27, 2015 at 6:58:35 AM, Jonne Haß (notifications@github.com) wrote:

I think some tests would be good so it doesn't break again ;)
